
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.73.5",
    version: "0.73.5 (2823574dcca80b00ce959e6882126e16)",
    buildSeed: 1657520884756,
};
