
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.70.0",
    version: "0.70.0 (0ef804bb117a708e6f843bb24d39d71e)",
    buildSeed: 1630553425567,
};
