
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.71.8",
    version: "0.71.8 (f5bcac8950cb3eced8cf84ce0c573385)",
    buildSeed: 1635503661214,
};
